version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8000:80
    depends_on:
      - mysql-db
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    container_name: db
    image: mysql:8.0
    restart: always
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    networks:
      backend:
        aliases:
          - mysql-db
networks:
  backend:
    name: backend-network